### ISSUE TITLE
Install failed

### ISSUE THREAD

**Issue by uniquePWD** [eosrei/emojione-color-font#10]
When I open the font file and tap Install on Ubuntu 16.04, the install fails.

**Comment by 13rac1** [comment]
@sabret00the The main cause of that issue I've experienced is if/when the font is already installed. Other potential causes are incorrect write permissions on `~/.fonts/` or a misconfigured font config. 

Please copy the file into `~/.fonts/` directly.

You can try running:

``` sh
gnome-font-viewer EmojiOneColor-SVGinOT.ttf
```

to actually see what the error is.

The directions previously were all command line. I may switch back to avoid this.

**Comment by uniquePWD** [comment]
Copying the file manually seems to have fixed the issue and now it all appears to be working. Thank you.

**Comment by 13rac1** [comment]
@sabret00the I've scripted the install process. How's it look now? https://github.com/eosrei/emojione-color-font#install-on-linux

**Comment by uniquePWD** [comment]
It's actually looking perfect @eosrei

**Comment by 13rac1** [comment]
Thanks!

**Comment by sabret00the** [comment]
So I switched to the PPA and it's kinda destroyed the fonts in my Firefox and made everything a Serif.
