### ISSUE TITLE
Linux install script fails when attempting to unzip the file

### ISSUE THREAD

**Issue by Scibearspace** [eosrei/emojione-color-font#12]
Following instructions in [readme.md](https://github.com/eosrei/emojione-color-font/blob/master/README.md) for install on linux 

As the title says.

when I do 
`unzip EmojiOneColor-SVGinOT.ttf.zip`

I get the following error
`Archive:  EmojiOneColor-SVGinOT.ttf.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of EmojiOneColor-SVGinOT.ttf.zip or
        EmojiOneColor-SVGinOT.ttf.zip.zip, and cannot find EmojiOneColor-SVGinOT.ttf.zip.ZIP, period.`

Solution was to use wget, not curl to download the zip archive.
New first line is.
`wget https://github.com/eosrei/emojione-color-font/releases/download/v1.0-beta/EmojiOneColor-SVGinOT.ttf.zip`

David.

Using Debian Jessy.

**Comment by 13rac1** [comment]
Ah, you don't have `curl` installed. Hmm... I think `wget` is always available, but I'll need to check some LiveCDs. Can you confirm if `curl` is installed or not?

**Comment by ghost** [comment]
Same boat here. `curl` installed and same error.

`
file EmojiOneColor-SVGinOT.ttf.zip 
EmojiOneColor-SVGinOT.ttf.zip: HTML document, ASCII text, with very long lines, with no line terminators
`

Turns out to be the HTML code for a redirect page to the .zip.

On Ubuntu 14.04.

**Comment by 13rac1** [comment]
Ah ha! I see what happened. Github moved it to their CDN. It wasn't on the CDN before when I wrote/tested the script.

Curl requires you to specify "Follow Redirects"

```
curl -L -O https://github.com/eosrei/emojione-color-font/releases/download/v1.0-beta/EmojiOneColor-SVGinOT.ttf.zip
```

Honestly, I'd rather recommend `curl` because it's a more advanced program, but that really doesn't matter in this case.

**Comment by 13rac1** [comment]
Hmm, plus on older Ubuntu's curl isn't installed by default.
