### ISSUE TITLE
Fonts should be in ~/.local/share/fonts/ instead of the deprecated ~/.fonts/

### ISSUE THREAD

**Issue by 13rac1** [eosrei/emojione-color-font#14]
`~/.fonts/` is deprecated. The new correct location is `~/.local/share/fonts/`. 

XDG Details: https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

```
#3. Create a XDG user font directory, if you don't have one:
mkdir -p ~/.local/share/fonts/
#4. Move the font into ~/.fonts/
mv EmojiOneColor-SVGinOT.ttf ~/.local/share/fonts/
```

I need to do further tests to make sure it works in all supported Linux distributions, before making any changes to the recommended install.

**Comment by 13rac1** [comment]
From the fontconfig docs:

> <dir prefix="default">
> 
> This element contains a directory name which will be scanned for font files to include in the set of available fonts. If 'prefix' is set to "xdg", the value in the XDG_DATA_HOME environment variable will be added as the path prefix. please see XDG Base Directory Specification for more details. 

And from the XDG Base Directory Specs:

> $XDG_DATA_HOME defines the base directory relative to which user specific data files should be stored. If $XDG_DATA_HOME is either not set or empty, a default equal to $HOME/.local/share should be used. 

`$XDG_DATA_HOME` is not set on my machine, so everything is using the default location. I'll need to check for the envvar and use the default if its not set. This may be getting too complex for a copy/paste installer.

**Comment by PaulBGD** [comment]
15.10, moving the file into the `~/.local/share/fonts/` and running `fc-cache -f -v` made it work, thanks for the help :+1:

**Comment by 13rac1** [comment]
Ah ha! Looks like I _am_ making an `install.sh`
