### ISSUE TITLE
Monospace fallback incorrect in Chrome with recommended font.conf

### ISSUE THREAD

**Issue by 13rac1** [eosrei/emojione-color-font#16]
![Chrome using a Serif font](https://cloud.githubusercontent.com/assets/195061/13726139/374a99f0-e86f-11e5-8b8a-4ad57dcf7c0f.png)

Chrome uses a serif font to display monospace text when _Emoji One Color_ is set as the default monospace font. It should use the next monospace font.

This is the correct display when the modified config is disabled making _DejaVu Sans Mono_ the default:
![Chrome with DejaVu Mono](https://cloud.githubusercontent.com/assets/195061/13726151/b62ea9d2-e86f-11e5-960a-1c06e2dc35c4.png)

**Comment by 13rac1** [comment]
The emoji characters which need to be overridden are only in _DejaVu Sans_, they do not appear in _DejaVu Serif_ or _DejaVu Mono_ according to my tests with the `fc-search-codepoint.py` script from: http://unix.stackexchange.com/a/268286/157461

``` sh
$ python fc-search-codepoint.py 😀
/usr/share/fonts/truetype/dejavu/DejaVuSansCondensed-BoldOblique.ttf
/usr/share/fonts/truetype/dejavu/DejaVuSans-BoldOblique.ttf
/usr/share/fonts/truetype/ttf-dejavu/DejaVuSansCondensed-Bold.ttf
/usr/share/fonts/truetype/ttf-dejavu/DejaVuSansCondensed-Oblique.ttf
/usr/share/fonts/truetype/ttf-dejavu/DejaVuSans-Bold.ttf
/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf
/usr/share/fonts/truetype/ttf-ancient-scripts/Symbola605.ttf
/usr/share/fonts/truetype/ttf-dejavu/DejaVuSansCondensed.ttf
/usr/share/fonts/truetype/ttf-dejavu/DejaVuSans.ttf
/usr/share/fonts/truetype/ttf-dejavu/DejaVuSansCondensed-BoldOblique.ttf
/usr/share/fonts/truetype/dejavu/DejaVuSansCondensed-Oblique.ttf
/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf
/usr/share/fonts/truetype/dejavu/DejaVuSansCondensed.ttf
/usr/share/fonts/truetype/ttf-dejavu/DejaVuSans-BoldOblique.ttf
/usr/share/fonts/truetype/dejavu/DejaVuSans-Oblique.ttf
/home/user/.local/share/fonts/TwitterColorEmoji-SVGinOT.ttf
/home/user/.local/share/fonts/EmojiOneColor-SVGinOT.ttf
/usr/share/fonts/truetype/ttf-dejavu/DejaVuSans-Oblique.ttf
/usr/share/fonts/truetype/dejavu/DejaVuSansCondensed-Bold.ttf
```

**Comment by 13rac1** [comment]
Ok, this updated `fonts.conf` gives priority to DejaVu Serif and Mono:

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">

<fontconfig>
  <!--
  Make Emoji One Color the fallback font for sans-serif, serif, and
  monospace, but give priority to the DejaVu serif/monospace fonts
  since they do not contain any emoji.
  Override any specific requests for Apple Color Emoji.
  -->
  <match>
    <test name="family"><string>sans-serif</string></test>
    <edit name="family" mode="prepend" binding="strong">
      <string>Emoji One Color</string>
    </edit>
  </match>
  <match>
    <test name="family"><string>serif</string></test>
    <edit name="family" mode="prepend" binding="strong">
      <string>DejaVu Serif</string>
      <string>Emoji One Color</string>
    </edit>
  </match>
  <match>
    <test name="family"><string>monospace</string></test>
    <edit name="family" mode="prepend" binding="strong">
      <string>DejaVu Sans Mono</string>
      <string>Emoji One Color</string>
    </edit>
  </match>
  <match>
    <test name="family"><string>Apple Color Emoji</string></test>
    <edit name="family" mode="prepend" binding="strong">
      <string>Emoji One Color</string>
    </edit>
  </match>
</fontconfig>
```

Should fix the issue. I'm going to leave this in place a while to see if it causes any problems on my machine.

Test before and after with: https://raw.githubusercontent.com/eosrei/emojione-color-font/master/full-demo.html

Any other testers appreciated!

**Comment by 13rac1** [comment]
:sob: There are a few characters in DejaVuSerif and DejaVu Sans Mono too. Not many, but I need to change them also.

**Comment by 13rac1** [comment]
Giving priority to DejaVu Serif or Mono won't fix this issue. I'm closing it to defer to the actual solution/workaround in #17

**Comment by 0matgal0** [comment]
A good workaround is to actually spoof the EmojiOne as Segoe UI Emoji. A lot of pages with emoji put Segoe in their CSS. Here how getemoji.com looks like with segoe installed:

![image](https://cloud.githubusercontent.com/assets/18264503/25312924/064a91e2-2825-11e7-9324-0d5c97c9afab.png)

As you can see no dejavu here.

**Comment by 13rac1** [comment]
Yes, that's the method used in the provided font config https://github.com/eosrei/emojione-color-font/blob/master/linux/fontconfig/56-emojione-color.conf#L135
