### ISSUE TITLE
Override/blacklist DejaVu emoji glyphs without making Emoji One Color the default font

### ISSUE THREAD

**Issue by 13rac1** [eosrei/emojione-color-font#17]
### The Problem

The current readme recommends creating/modifying the user's _fontconfig_ `fonts.conf` to make _Emoji One Color_ the primary fallback font for `sans-serif`, `serif` and, `monospace` font families. This causes a number of issues including #1, #5, and #16. Ideally the _DejaVu_ font family would stay the default and _Emoji One Color_ would override/replace the emoji included in _DejaVu Sans_.

According to my tests in https://github.com/eosrei/emojione-color-font/issues/16#issuecomment-195839174, only _DejaVu Sans_ has the actual emoji characters which cause this problem:
![ohnoitsdejavu](https://cloud.githubusercontent.com/assets/195061/13726176/0a065cca-e871-11e5-8d39-c77b974aa257.png) which is what happens when the recommended `fonts.conf` is not installed.

A nice solution would be to blacklist the _DejaVu Sans_ glyphs...
### Blacklisting glyphs

There has been a number of requests for an option to "blacklist glyphs" or "create virtual fonts" in fontconfig over the years, but there is no current implementation AFAIK. (Too much detail follows, but this is a good place to keep the research.) 😉

> Mixing arbitrary unicode ranges into a virtual font
> might be needed when some fonts have just a few bad
> characters [eg numbers], but normally mixing would be
> by language.
> 
> Ideas on how to approach it [if not done already]?

src: https://lists.freedesktop.org/archives/fontconfig/2004-October/001045.html

> Blacklisting glyphs in fonts has been a long standing wish for lots of
> people, and the patch for fontconfig was even written once I think, but
> it was never applied. Fontconfig people are just blaming the fonts with
> all the different scripts. But as said before, it'll have to be
> fontconfig which needs to be patched, since fonts won't do anything as
> long as font substitution isn't available everywhere (and even then it
> remains to be seen).

src: https://sourceforge.net/p/dejavu/mailman/message/9671050/

> I remember that once upon a time the whole issue of making it possible
> for FontConfig to blacklist glyphs from
> fonts was discussed.
> 
> The idea was that it is easy and fast to write a few lines of XML into
> a FontConfig .conf file while it is slow and
> laborious to remove glyphs from a font.
> 
> Perhaps now is the time to actually implement this functionality in FontConfig?

src: https://lists.freedesktop.org/archives/fontconfig/2008-January/002847.html
Followed up by:

> Sure, Pango totally uses fontconfig to determine if a font supports a
> character.  So this can completely be fixed in fontconfig.  Someone
> needs to go finish the patch and pass it through Keith I think.

src: https://lists.freedesktop.org/archives/fontconfig/2008-January/002850.html

> - Finish patch for fontconfig to allow configuration to disable
>   certain Unicode codepoints per font.  The write such configuration for
>   the crappy glyphs.
> 
> Pick whichever you prefer and just do it.

src: https://mail.gnome.org/archives/gtk-i18n-list/2007-December/msg00007.html
### Solutions

As much fun as it would be to go down another rabbit hole, I don't have the time to patch fontconfig right now. Plus, backwards compatibility would still be an issue. The recommended solution is to remove the offending glyphs.

> Actually IMO if the Latin glyph are crappy, removing them is the single
> most correct solution.

src: https://lists.freedesktop.org/archives/fontconfig/2008-January/002846.html

This means a fork of _DejaVu Sans_ is probably the answer. Any other ideas?! 😎

**Comment by 13rac1** [comment]
Yes, still looks like the best solution. Microsoft and Apple probably ship emoji characters in a separate font for this reason.

Short term goal: _DejaVu Sans_ without emoji to ship with this font.
Long term goal: a _DejaVu Emoji_ font in a pull request.

Follow along here: https://github.com/eosrei/dejavu-fonts/tree/emoji

**Comment by 13rac1** [comment]
Just found some emoji in _DejaVu Serif_ and _DejaVu Sans Mono_. I need to fork the whole family! Yay.
![DejaVu Serif too](https://cloud.githubusercontent.com/assets/195061/13731206/cd107110-e920-11e5-825c-97a98b538447.png)

**Comment by 13rac1** [comment]
This font: https://github.com/eosrei/dejavu-fonts/commit/46ba8581cd599b4e4e247c5d3d19e02aa99f73fa with the following `fonts.conf` seems to work:

```
<fontconfig>
  <match>
    <test name="family"><string>sans-serif</string></test>
    <edit name="family" mode="prepend" binding="strong">
      <string>DejaVu Sans No Emoji</string>
      <string>Emoji One Color</string>
    </edit>
  </match>
  <match>
    <test name="family"><string>Apple Color Emoji</string></test>
    <edit name="family" mode="prepend" binding="strong">
      <string>Emoji One Color</string>
    </edit>
  </match>
  <match>
    <test name="family"><string>Segoe UI Emoji</string></test>
    <edit name="family" mode="prepend" binding="strong">
      <string>Emoji One Color</string>
    </edit>
  </match>
</fontconfig>
```

**Comment by 13rac1** [comment]
I've found a much better solution to this issue: _Bitstream Vera_! It's the basis for _DejaVu_ and doesn't include all of these characters needing to be overridden. _Bitstream Vera_ is going to be the default install recommendation going forward. _Noto_ can work if modified to remove a few emoji from the regular fonts which IMO should be moved to _Noto Emoji_ I'll open on that project about it.

**Comment by qnub** [comment]
Have same view 

![](https://cloud.githubusercontent.com/assets/195061/13726176/0a065cca-e871-11e5-8d39-c77b974aa257.png)

**Comment by 13rac1** [comment]
DejaVu is the default font family for Linux. My provided fontconfig is the solution for this.

**Comment by qnub** [comment]
fonts.config installed with this tdistributio give result from this screenshot.

**Comment by 13rac1** [comment]
Please open a new issue with the following details:
- Linux distribution and version
- Firefox version
- The output from running the unit tests, both files are required: https://github.com/eosrei/emojione-color-font/tree/cc38faa4eb3cb04a44aa35221c913310fab49699/linux/tests
