### ISSUE TITLE
Overlapping text in some applications

### ISSUE THREAD

**Issue by tatokis** [eosrei/emojione-color-font#19]
First of all, I would like to congratulate you on your hard work. It's great to finally see proper emojis on linux.

After installing the font, there is some overlapping text on applications such as Liferea and Geary.
![3bb777f7eb65](https://cloud.githubusercontent.com/assets/6003656/13744064/380b3f36-e9ee-11e5-94a9-8bed45a4a9bd.jpg)

System is Ubuntu 15.10, Unity 7.3.3 with Ambiance, and according to screenfetch, the (default?) font 
is Ubuntu 11. It also happens on AwesomeWM running on a separate X display.

![60cca2e1b744](https://cloud.githubusercontent.com/assets/6003656/13744447/74dd89ee-e9f0-11e5-8fe2-77e83aba2bd9.jpg)

Font was installed in ~/.local/share/fonts automatically using the built in font viewer, and the config was copied from the OMG! Ubuntu! article.

Apologies if this has been reported before, I couldn't any issues related to mine while going through existing ones.

**Comment by 13rac1** [comment]
Thanks a lot!

This is a separate issue, but clearly related to #2. First thing, remove the `fonts.config`. That'll fix the main problem. You'll find DejaVu Sans takes precedence, but the spaces _should_ all be correct. 

Edit: More details later, just didn't want to leave you hanging. :D

**Comment by 13rac1** [comment]
Short term I am going to release two versions of the font for linux. One with a sans-serif and serif space width and the other with a monospace space width. Total waste of 6MB for few bytes difference. Long term the fix is: #17 Please let me know if you have any other ideas, thank you!

**Comment by 13rac1** [comment]
Oh, I forgot about this: https://github.com/eosrei/emojione-color-font/issues/2#issuecomment-193206871 It's absolutely the same issue. Please follow that one and you'll be notified when I fix it.

**Comment by tatokis** [comment]
Alright, thanks a lot!

**Comment by 13rac1** [comment]
@tatokis I determined changing the default font from DejaVu to Bitstream Vera then making Emoji One Color secondary solves all of these font rendering issues. Bitstream Vera doesn't have all of the extra characters to override. Please try it out: https://github.com/eosrei/emojione-color-font/commit/24b65391c1f02f8ff57b7b4f9c12f94550bac0ca It's a much better solution than forking DejaVu. There's a few issues with Noto, but I'd like to make it an option also.
