### ISSUE TITLE
Some programs unable to display proper text: KeePass

### ISSUE THREAD

**Issue by DistantThunder** [eosrei/emojione-color-font#25]
You can see for yourself. The program is KeePass.

![font_render_problem](https://cloud.githubusercontent.com/assets/3923810/14062325/2c5a314a-f39b-11e5-9d31-8af0ea9b254e.png)

**Comment by 13rac1** [comment]
Have you [installed v1.0-beta3](https://github.com/eosrei/emojione-color-font/releases)? This looks exactly like #5 and #18 which was discussed in detail in #2 and fixed in Beta3.

**Comment by DistantThunder** [comment]
Ah yes, the beta3 works as intended, thanks!

**Comment by 13rac1** [comment]
Great! Let me know if you find any other issues. I'm waiting to hear if there are any other breaking issues before creating a non-beta v1.0. Seems really close, but with all the font conflicting hassles I've had I want to wait.
