### ISSUE TITLE
Consider Chocolatey as a Windows distribution channel

### ISSUE THREAD

**Issue by lofidevops** [eosrei/emojione-color-font#27]
Chocolatey is a distribution tool for Windows applications, including many free software applications (for example, https://chocolatey.org/packages/pidgin). It allows an end-user to get application updates somewhat like using apt or yum on GNU/Linux.

I have not explicitly seen it used for fonts, but it basically script-based and seems like a viable platform to deliver updates, which I imagine will continue apace for a font based on Emoji One.

https://github.com/chocolatey/choco/wiki/ChocolateyFAQs
https://github.com/chocolatey/choco/wiki/Moderation

**Comment by 13rac1** [comment]
A Chocolatey package is blocked by #15. Any ideas on that?

I'm all for packages for everything, although, right now I only have time to personally maintain the Debian/Ubuntu deb package. Long term, I'd like deb, rpm, chocolatey and homebrew for both emoji fonts. An Arch AUR already exists for both.

**Comment by 13rac1** [comment]
#15 was closed by #47. The Windows install requires Python to build custom fonts, but works well. The entire process could be automated using a Chocolately install now.

**Comment by 13rac1** [comment]
Packaging was requested. This project is dead long term due to upstream licensing, see #71
