### ISSUE TITLE
Vertical alignment slightly too low

### ISSUE THREAD

**Issue by 13rac1** [eosrei/emojione-color-font#3]
Vertical alignment slightly too low, compare to selection box.
![vertical-too-low](https://cloud.githubusercontent.com/assets/195061/13365243/c1b39c92-dc88-11e5-8156-59845c4ef688.png)

Verses DejaVu.
![vert-align](https://cloud.githubusercontent.com/assets/195061/13365705/8b62d42a-dc8b-11e5-9c8b-efb7a02f1a86.png)

Some test html:

```
gO <a href="test.html">gO 😀 🐵 <span style="font-family: 'DejaVu Sans';">😀 🐵</span></a>
```

Probably something to fix in SCFBuild, hopefully it can be automated.

**Comment by edent** [comment]
Also on `⚠`
![emoji line](https://cloud.githubusercontent.com/assets/837136/13490724/fdc295d4-e125-11e5-81a1-117997f9635e.png)

**Comment by 13rac1** [comment]
Hmm... Yes, I'll see about fixing this right now.

**Comment by 13rac1** [comment]
Solved the problem as a quick hack:
![Fixed in FF and Chrome](https://cloud.githubusercontent.com/assets/195061/13537014/b41de24e-e1f7-11e5-8387-571cc16ba8fc.png)

Actual fix early next week.
