### ISSUE TITLE
Making color Emojis show up everywhere on Linux (not just in browser)?

### ISSUE THREAD

**Issue by kq01526** [eosrei/emojione-color-font#30]
> @eosrei wrote in [README.md](https://github.com/eosrei/emojione-color-font/blob/master/README.md):
> 
> [...] The font works in all operating systems, but will currently only show color emoji in Mozilla Firefox and Thunderbird. This is not a limitation of the font, but of the operating systems and applications. [...]

Why is that?

What exactly is the limitation in Linux desktop operating systems and applications?

I saw you also posted in https://github.com/googlei18n/noto-emoji/issues/36.

But what exactly needs to be done to make color Emojis show up everywhere on Linux (not just in the browser)?

**Comment by 13rac1** [comment]
The details are well explained by Behdad in that noto-emoji issue: Cairo doesn't support CBDT/CBLC or SVGinOT fonts. I've made two SVGinOT color fonts and worked out a viable fontconfig, but I don't have the time or current knowledge to patch the Linux font render system. I'm happy to help, but there's no much I can do at this point.
