### ISSUE TITLE
[firefox] gfx.font_rendering.fontconfig.fontlist.enabled must remain false

### ISSUE THREAD

**Issue by coopsmoss** [eosrei/emojione-color-font#31]
First of all, thanks a lot for these. Only issue is that when I do:

gfx.font_rendering.fontconfig.fontlist.enabled = false
restart
gfx.font_rendering.fontconfig.fontlist.enabled = true
restart
The problem with the fonts comes back

I'm using Firefox 45.0.1 on Ubuntu 15.10.
I'm just leaving it as false at the moment, not sure if it's having any detrimental affects.

Cheers

**Comment by 13rac1** [comment]
Thanks for creating an issue about this! The solution in the README worked for me and a number of others. Hmm... Now that you mention it, I realize while it fixes the actual problem, bold fonts are just far too **bold** with it set to true. I've actually got it set to false for that reason on my machine.

Are there relevant details you could add to @salty-horse 's issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1254245 ?

Related to #1

**Comment by 13rac1** [comment]
True:
![fontlist-true](https://cloud.githubusercontent.com/assets/195061/14407655/a139c084-fe86-11e5-915e-198a81317e31.png)

False:
![fontlist-false](https://cloud.githubusercontent.com/assets/195061/14407658/a5bd3aaa-fe86-11e5-98e1-87320fa01168.png)

The font weight seems doubled with it True.

**Comment by 13rac1** [comment]
This should be fixed according to: https://bugzilla.mozilla.org/show_bug.cgi?id=1245811#c47

**Comment by 13rac1** [comment]
Firefox 46 [was just released](https://www.mozilla.org/en-US/firefox/46.0/releasenotes/), but this regression isn't fixed until Firefox 47. I'll update the readme to say users of Firefox <47 should set this to false.

**Comment by salty-horse** [comment]
Firefox 47's planned release date is 2016-06-07.

**Comment by PhilippBaschke** [comment]
I am using the Firefox Developer Edition (currently at **48.0a2 (2016-05-10)**) and the fonts only look right (like they used to look before) when I set `gfx.font_rendering.fontconfig.fontlist.enabled` to `false`. :cry:

**Comment by 13rac1** [comment]
Thanks @PhilippBaschke I'll update the readme.

**Comment by NoXPhasma** [comment]
When I set `gfx.font_rendering.fontconfig.fontlist.enabled` to `false` fonts will be displayed correctly, but some sites will crash Firefox. For example Wikipedia always crashes Firefox. When I set `gfx.font_rendering.fontconfig.fontlist.enabled` back to `true` nothing crashes.

Linux Mint 17.3 Rosa - Firefox 46/47b

**Comment by 13rac1** [comment]
@NoXPhasma If you can reproduce this, especially without my font enabled, I suggest opening a new issue on the mozilla bug tracker.

**Comment by NoXPhasma** [comment]
@eosrei This does indeed happen even your font isn't installed. Should have check that before.

**Comment by NoXPhasma** [comment]
Just a heads up on my issue, this doesn't happen in Firefox 48.0a2 (2016-06-02).

**Comment by salty-horse** [comment]
I believe this is the fix for the crash: https://bugzilla.mozilla.org/show_bug.cgi?id=1266341

**Comment by 13rac1** [comment]
Additional related bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1306715 Thx @salty-horse

**Comment by perk11** [comment]
Still had to change this setting on Firefox 53 for it to not change default font

**Comment by 13rac1** [comment]
Yes, it's a known issue: https://github.com/eosrei/emojione-color-font#known-issues

**Comment by salty-horse** [comment]
This fix will break in Firefox 55 (can test with Nightly). The related changes:

https://bugzilla.mozilla.org/show_bug.cgi?id=1119128
https://bugzilla.mozilla.org/show_bug.cgi?id=1285533
