### ISSUE TITLE
Create an alternate version using Google Emoji (Noto Emoji)

### ISSUE THREAD

**Issue by kurisubrooks** [eosrei/emojione-color-font#32]
I'd absolutely love it if you could make a version that used Google's Noto Emoji font. 
Pretty please 🙇 🙇

**Comment by 13rac1** [comment]
Thanks for your interest! 😉 I cannot. The Noto Emoji repo contains the full set of bitmap images, but many of the SVGs needed to generate a SVGinOT version of the font are missing. 😭 [There are only 872 SVG files](https://github.com/googlei18n/noto-emoji/tree/master/svg) verses the 1,669 SVGs in this font. Plus, [skin tone diversity graphics are missing completely from Noto Emoji](http://blog.emojipedia.org/android-6-0-1-emoji-changelog/), even in the bitmaps.

I've put 100s of hours into this font, [Twitter Color Emoji](https://github.com/eosrei/twemoji-color-font) and [the build system](https://github.com/eosrei/scfbuild) for both fonts. I don't have time to make more emoji fonts right now.

I'll update this issue if anything changes.

**Comment by Crissov** [comment]
JFTR, the Noto Emoji SVG issue is tracked at https://github.com/googlei18n/noto-emoji/issues/30 and still not fixed.
