### ISSUE TITLE
Bitstream Vera doesn't contain regional accented characters

### ISSUE THREAD

**Issue by corvidism** [eosrei/emojione-color-font#36]
Hi,

I installed the font through the ppa. Emojis work, but because the Bitstream Vera family doesn't contain any regional characters all applications that use the system default (e.g. Firefox) look like crap. :/ Uninstall fixes it (thankfully).

Can you tell me what setting/file are you changing to set the system default? I looked at `install.sh`, but I can't find it. (I understand Ubuntu users should be able to change the font through system settings, but I'm using Xubuntu and apparently this damn system doesn't have a GUI option for it.)

Thanks,

C.

(Also, could you maybe add a note about this to Known Issues? I bet I'm not the only non-english-xfce-user-in-need-of-emojis out there :] )

**Comment by 13rac1** [comment]
Firefox should fall back to DejaVu, it's still available and provides the glyphs/characters you need.

```
$ fc-match -s sans | head -n3
Vera.ttf: "Bitstream Vera Sans" "Roman"
EmojiOneColor-SVGinOT.ttf: "Emoji One Color" "Regular"
DejaVuSans.ttf: "DejaVu Sans" "Book"
```

The enabled fontconfig settings are smlinked in `/etc/fonts/conf.d/`. Install.sh creates a file named `56-emojione-color.conf` available here: https://github.com/eosrei/emojione-color-font/blob/d1c607bc442b6bb3d9536c0b38f9befb396a3573/linux/fontconfig/56-emojione-color.conf

**Comment by 13rac1** [comment]
Can you link/screenshot an example of where the incorrect font is loading? 

BTW The only **for sure** solution to all of this is to manually subset DejaVu using nototools to remove all of the emoji characters.

**Comment by 13rac1** [comment]
This may be a XFCE specific issue. I'm running MATE and have no issue with fall back (Bitstream Vera -> EmojiOne Color -> DejaVu Sans) to load combining diacritical marks.
Details: https://en.wikipedia.org/wiki/Combining_character
Demo: http://www.user.uni-hannover.de/nhtcapri/combining-marks.html
Screenshot:
![combining diacritical marks demo](https://cloud.githubusercontent.com/assets/195061/15861123/7d8c4936-2c80-11e6-95e6-3870f3e78a5f.png)

Have you tried the [known issue workaround](https://github.com/eosrei/emojione-color-font#known-issues)?

> Open `about:config` set `gfx.font_rendering.fontconfig.fontlist.enabled` to `false`

**Comment by 13rac1** [comment]
I'm closing this due to lack of response and that AFAIK the solution is already listed in the readme.

Related to #31
