### ISSUE TITLE
[Suggestion] emojione installation in Gentoo and Gentoo-based distros

### ISSUE THREAD

**Issue by jorgicio** [eosrei/emojione-color-font#38]
Hi!
I'm a Gentoo user and also maintain an overlay (non-official repo), and also maintain the package for your project.
So there are the instructions to install and to add to your README:

First install layman (if not installed) with the USE="git" enabled, with Portage. (Is enabled by default, btw)

`emerge layman`

Then, add my repo:

`layman -s jorgicio`

and then install the package:

`emerge emojione-color-font`

It solves dependencies.

Thanks!

**Comment by 13rac1** [comment]
Great! Thanks! I'll add it to v1.1

**Comment by jorgicio** [comment]
Thanks to you too! I'll wait for that, then. Greetings!

**Comment by 13rac1** [comment]
No, need to close yet. I'll close when I add it.

**Comment by jorgicio** [comment]
Oh, ok, ok, got it. Thanks.

**Comment by 13rac1** [comment]
@jorgicio Is there a Gentoo package for https://github.com/eosrei/twemoji-color-font ? I like to update them in sync.

**Comment by jorgicio** [comment]
Not yet, I didn't know about its existence, so I'll do the package for that.

**Comment by 13rac1** [comment]
Awesome thanks! I made the EmojiOne font first, but the Twitter one was easy since I already had the build system setup that I decided I'd do it too. They both have their pros/cons.

**Comment by jorgicio** [comment]
Ok, so can I have installed both or only one or both? Are there conflicts?

BTW, package created, named twemoji-color-font. The installation way is the same as I mentioned with emojione-color-font, just with another package name.

**Comment by 13rac1** [comment]
You can install both, but you can only have one default via my provided fontconfig. If you install both fontconfigs, then the result is undefined. Haha!

FWIW I named the Ubuntu Launchpad packages to match the existing font package structure and specifically call out the provided color font format (since I plan to make SBIX and CBLC/CBDT format fonts also) `fonts-emojione-svginot`: https://launchpad.net/~eosrei/+archive/ubuntu/fonts

**Comment by jorgicio** [comment]
Ok, got it. However, I tried enabling both and are working but a bit laggy. Thanks for the advice.
I'll wait for future releases to maintain ;)
