### ISSUE TITLE
[Linux] Steam client shows number icons instead of numbers in price tag.

### ISSUE THREAD

**Issue by NoXPhasma** [eosrei/emojione-color-font#39]
Font version:  v1.1
Screenshots: Wrong icons: https://i.imgur.com/Lsuze7E.png 
![Wrong icons](https://cloud.githubusercontent.com/assets/195061/15969471/187b232a-2ee5-11e6-983f-40555b9997b6.png)

Expected display: https://i.imgur.com/cMVT4f1.png
![Expected display](https://cloud.githubusercontent.com/assets/195061/15969483/2019ff2a-2ee5-11e6-8843-659f2d997fa9.png)

Operating system: Linux Mint 17.3
Steps to reproduce Install Font v1.1, start the Steam client on Linux and go to the main shop site.

Since the update to font version 1.1 (Installed via PPA), the Steam client shows number icons instead of numbers on some price tags. The Steam client uses Chromium as Browser Backend.

**Comment by 13rac1** [comment]
Confirmed! HAHA! 🤣 This is getting ridiculous with these numbers (#37, #35). I know what is causing it in the fontconfig, but it's AFAIK a correct config.

I'm going to just disable the numbers again to avoid this until I can implement #22.

**Comment by 13rac1** [comment]
Workaround in V1.2. PPA is building.

**Comment by NoXPhasma** [comment]
Fixed 👍
