### ISSUE TITLE
Can't replace font system wide OSX 10.11

### ISSUE THREAD

**Issue by AngelAlvarado** [eosrei/emojione-color-font#4]
It seems to be a new security feature (rootless "System Integrity Protection")  added to 10.11: 

"You can't modify anything in /System, /bin, /sbin, or /usr (except /usr/local);"

http://apple.stackexchange.com/questions/193368/what-is-the-rootless-feature-in-el-capitan-really

**Comment by 13rac1** [comment]
Ah ha!. I test with a 10.10 install. Haven't created a 10.11 install yet. The font should still work correctly if installed via Fontbook if specifically requested such as on: http://eosrei.github.io/emojione-color-font/full-demo.html

**Comment by 13rac1** [comment]
I'll generate a version of this font using the same internal name as the Apple Emoji font so it can override the original.

**Comment by 13rac1** [comment]
Both versions of the font are now available for download here: https://github.com/eosrei/emojione-color-font/releases Install instructions: https://github.com/eosrei/emojione-color-font#install---os-x

**Comment by AngelAlvarado** [comment]
Cool, it works! Thank you.
