### ISSUE TITLE
How do I get my old symbols back?

### ISSUE THREAD

**Issue by malcolmocean** [eosrei/emojione-color-font#43]
I downloaded this on ubuntu basically because I wanted a fallback font for the symbols my font didn't already support. But I don't actually like that all of my old symbols were overwritten. U+25b6 became a light arrow in a circle, for instance, instead of a nice heavy black right-facing arrow. (I'm using Chrome, so I don't get the colors)

I think that all I need to do is undo the part where Bitstream Vera Sans was made the default font, but I can't actually find where to do that. I downloaded Unity Tweak Tool, but in Fonts it says I'm using Ubuntu Regular.

On net, I'd rather uninstall everything than keep things the way they are... but ideally I could still use this font for places no other font supports.

**Comment by 13rac1** [comment]
Uninstall the package or run the uninstall.sh if you installed manually.
Then download the basic zip file version and install like any other font.
