### ISSUE TITLE
Firefox shows some colour emoji in the address bar, but not all

### ISSUE THREAD

**Issue by richardjharris** [eosrei/emojione-color-font#44]
I installed fonts-emojione-svginot (1.2-1) and fontconfig (2.11.94-0ubuntu1) from the eosrei/fonts PPA onto an Ubuntu 16.04 system.

When I visit http://eosrei.github.io/emojione-color-font/full-demo.html with Firefox 47.0, all of the emoji are displayed correctly. They are always shown correctly inside web pages. The Ubuntu window titlebar also renders all emoji correctly including regional indicators and face+color combos as a single glyph (albeit in black and white)

However the rest of the Firefox GUI is inconsistent. For the tab title, address bar, search bar, history and other GUI, most of the emoji appear in black and white, and country flags are shown as two regional indicator characters. Faces with skin colour joiners are shown as two glyphs. The only exception are 'New in Unicode 9.0' emojis which are rendered correctly and in colour everywhere. Presumably because no other installed font supports those glyphs.

I tried setting my Firefox default sans-serif font to EmojiOne but it didn't change anything. Any idea how to get Firefox to use the right font?

**Comment by richardjharris** [comment]
I apologise that this may not be relevant to the emojione git repo, I wasn't sure where else to ask.

**Comment by 13rac1** [comment]
I just noticed: I can't believe this repo is up to 44 issues 🤤

Haha, please check #1 for potential fixes.

**Comment by 13rac1** [comment]
This may be the solution: https://github.com/eosrei/emojione-color-font/issues/1#issuecomment-189178254

**Comment by richardjharris** [comment]
https://github.com/eosrei/emojione-color-font/issues/31 solved the issue for me. Thanks! Closing

**Comment by 13rac1** [comment]
Great! That issue has been a thorn in my side. I wish there was something I could do.
