### ISSUE TITLE
Add how to delete the font in linux and similarly on all other platforms in readme.md

### ISSUE THREAD

**Issue by fuaxio** [eosrei/emojione-color-font#45]

**Comment by vyp** [comment]
uninstall.sh/package manager (and the system font manager for OS X/Windows)?

**Comment by 13rac1** [comment]
@vyp Yes, I generally agree.

I don't even have _install_ directions on OS X and Windows right now. The fonts install and uninstall like any other font, the details of which are out-of-scope of my docs IMO.

@fuaxio Does this work?

```
# Uninstall on Linux:
$ ./uninstall.sh
```

I'm not sure it's necessary though..
