### ISSUE TITLE
[Linux] Chrome and Firefox do not display number emoji correctly

### ISSUE THREAD

**Issue by kgizdov** [eosrei/emojione-color-font#46]
I currently have no issues with this font except for this one. I'm guessing the number emoji are overridden somewhere, but I wonder why no other emojis are. Everything else looks fine.
- Font version: 1.2
- Screenshots:
  Chrome
  ![chrome_emoji](https://cloud.githubusercontent.com/assets/3164953/16484968/1f09b948-3eb4-11e6-8925-68e17727aaf8.png)
  Firefox
  ![firefox_emoji](https://cloud.githubusercontent.com/assets/3164953/16484973/23a1ffb0-3eb4-11e6-8a65-bc7588896ab2.png)
- Operating system: Arch Linux x64
- Steps to reproduce:
1. Install font
2. Open Chrome or Firefox
3. visit a page that contains number emoji

**Comment by 13rac1** [comment]
Thank you for the detailed bug report!

This is currently intentional. The glyphs were disabled in https://github.com/eosrei/emojione-color-font/commit/e1a34da33493ee2966012cc6467ad519dfc518d3 for [#40 [Linux] Inconsistently parsed fontconfig causes font selection problems](https://github.com/eosrei/emojione-color-font/issues/40) (Help wanted!) If I revert the commit, then #35, #37, #39 and more will happen again.

**Comment by kgizdov** [comment]
Well, that's a good point, but #40 on my Arch looks like this and everything works fine.

``` sh
❯ fc-match -s sans
Vera.ttf: "Bitstream Vera Sans" "Roman"
EmojiOneColor-SVGinOT.ttf: "EmojiOne Color" "Regular"
DejaVuSans.ttf: "DejaVu Sans" "Book"
DejaVuSans-Bold.ttf: "DejaVu Sans" "Bold"
DejaVuSans-Oblique.ttf: "DejaVu Sans" "Oblique"
DejaVuSans-BoldOblique.ttf: "DejaVu Sans" "Bold Oblique"
n019003l.pfb: "Nimbus Sans L" "Regular"
... etc
```

For #35, #37, #39, I'm really not sure why UTF-8 emoji glyphs would appear instead of numbers - those are separate symbols, I believe. Could this all be something else?

**Comment by 13rac1** [comment]
The programs in those issues all implement their own fontconfig parsing, but as far as I understand, they don't follow the spec for `prepend_first`. You can see mpv's debug output here where it defaults to the incorrect default font: https://github.com/eosrei/emojione-color-font/issues/37#issuecomment-220590538 

> everything works fine.

Run Evolution, MPV or Steam with version 1.1 of the font and you can reproduce these issues.

> I'm really not sure why UTF-8 emoji glyphs would appear instead of numbers - those are separate symbols, I believe.

These numpad emoji require [font ligatures](https://en.wikipedia.org/wiki/Typographic_ligature#Computer_typesetting) to work. Font ligatures only work if _all_ glpyhs used to create the ligature are in the font. I need to have both the empty numpad emoji and a regular non-emoji number so they can be combined to create a numpad number.

> Could this all be something else?

Yes, but this is **so far** the only solution in my tests on all three programs in two Linux distributions. I gladly accept a better solution though.

I've suggested a possible solution (or rather long term workaround for the MPV, Evolution, and Steam bugs) in #40 at: https://github.com/eosrei/emojione-color-font/issues/40#issuecomment-229722645

Let's move further discussion on this to #40. Thanks!
