### ISSUE TITLE
Remove BLACK LARGE SQUARE and other black glyphs from font

### ISSUE THREAD

**Issue by erjiang** [eosrei/emojione-color-font#52]
Using version 1.2 2160610 on Ubuntu 14.04.

I suggest removing BLACK LARGE SQUARE and possibly other monochrome glyphs from this font. Old fonts supported it fine because there's no color, but including it in the font causes some problems without any obvious benefit to me.

Problem 1: There's are some older usages of BLACK LARGE SQUARE in web apps that set the CSS color property. These all show up as black now. I understand this is a bug that they should fix and have reported it where I can.

Problem 2: On apps that fall back to the monochrome outlines, BLACK LARGE SQUARE shows up as WHITE LARGE SQUARE. For other similar symbols, the outline is harder to read than what the user previously had.

You could special case this and similar glyphs by making the fallback have a solid fill instead of just an outline, but it seems like it would be easier to just exclude it.

![selection_106](https://cloud.githubusercontent.com/assets/321497/17499208/d8aa4404-5d80-11e6-9096-b6cc8457aea7.png)

Other glyphs that should also be reconsidered:

🎵 🎶 〰️ ➰ ✔️ 🔃 ➕ ➖ ➗ ✖️ 💲 💱 ©️ ®️ ™️▪️◼️◾️🕐 🕑 🕒 🕓 🕔 🕕 🕖 🕗 🕘 🕙 🕚 🕛 🕜 🕝 🕞 🕟 🕠 🕡 🕢 🕣 🕤 🕥 🕦 🕧

**Comment by 13rac1** [comment]
Thank you for the detailed issue. :)

This problem is due to #22 and realistically is a bug in the build system.

**Comment by 13rac1** [comment]
The other reason for this is that the b&w glyphs are automatically generated from the color versions: https://github.com/eosrei/emojione-color-font/blob/9c2b5260aee756744ec7d19f46d858a8d3f03643/Makefile#L98-L111 It took me a long time to work out this method. Any adjustments/changes to make them better is appreciated.

**Comment by erjiang** [comment]
I understand that the b&w glyphs are auto-generated. Maybe some glyphs can have a "override" B&W SVG, and the build will skip auto-generating B&W versions for those?

Since you are using potrace, there may be something clever that could be done with doing a b/w threshold trace... but that seems unreliable.  Or glyphs that get traced into just one shape (monochrome) are filled in instead of being just an outline.

**Comment by 13rac1** [comment]
> Maybe some glyphs can have a "override" B&W SVG, and the build will skip auto-generating B&W versions for those?

It's an option, but not something I want to deal with right now. Fontforge cannot handle many of these SVGs in their default format, so they need to be simplified. I'm open to PRs for it though.

> b/w threshold trace
> I've adjusted that many times. The current settings are reliable, but something better would be awesome.

I'm closing this for now. The primary issue is described and will be fixed by #22. Maybe that will be enough? Please try additional methods and open a PR if you find something better. Thank you!
