### ISSUE TITLE
Run ttfautohint on font

### ISSUE THREAD

**Issue by 13rac1** [eosrei/emojione-color-font#53]
Windows cannot hint fonts, so: https://www.freetype.org/ttfautohint/

**Comment by 13rac1** [comment]
Default 16.04 version segfaults:

```
$ ttfautohint -s EmojiOneColor-SVGinOT.ttf EmojiOneColor-SVGinOT-Win.ttf
Segmentation fault (core dumped)
```

Current Yakkety build installed in 16.04 works: https://launchpad.net/ubuntu/+source/ttfautohint/1.5-1ubuntu1/+build/9699986

```
$ ttfautohint -s -v -c -W EmojiOneColor-SVGinOT.ttf EmojiOneColor-SVGinOT-Win.ttf
  1835 glyphs
    10% 20% 30% 40% 50% 60% 70% 80% 90%
```

**Comment by be5invis** [comment]
Well it is not “Windows cannot hint fonts”, but “Windows interprets the font data as-is”.

**Comment by 13rac1** [comment]
Project EOL, issue moved to: https://github.com/eosrei/twemoji-color-font/issues/40
