### ISSUE TITLE
RPM packaging contribution

### ISSUE THREAD

**Issue by guoyunhe** [eosrei/emojione-color-font#54]
I made a RPM packaging use openSUSE Build Service. Supports openSUSE, Fedora, RHEL, CentOS, ScientificLinux and SLE.

http://software.opensuse.org/download.html?project=home%3Aguoyunhebrave&package=emojione-color-font

**Comment by 13rac1** [comment]
Awesome! I'll test it out and add to README on both fonts. Thanks!

**Comment by 13rac1** [comment]
I'm not sure how to handle this contribution. It doesn't install the fontconfig to make the font work as the default emoji font. It just installs the font as a system font. I'm happy to see a package doing this, but I cannot recommend it in the README unless it works like everything else.

**Comment by 13rac1** [comment]
Closing due to lack of response.

**Comment by danimesq** [comment]
@guoyunhe
