### ISSUE TITLE
fonttools upgrade fails when using the windows install script

### ISSUE THREAD

**Issue by GramMKII** [eosrei/emojione-color-font#55]
if fixed it by using
`pip install --upgrade git+https://github.com/behdad/fonttools.git#egg=fonttools`

instead of
`pip install --upgrade https://github.com/behdad/fonttools/archive/master.zip`

in line 44 of install.bat

**Comment by 13rac1** [comment]
We don't need to use the master branch anymore the default version of fonttools from pip installs the required features. I will leave this open until I confirm and update the install script. Thank you!
