### ISSUE TITLE
Provide NotoColorEmoji compatible format for Chrome on Linux and Android

### ISSUE THREAD

**Issue by m13253** [eosrei/emojione-color-font#57]
Chrome on Linux can already display color emoji by installing `NotoColorEmoji.ttf`.
The source code of which is available at https://github.com/googlei18n/noto-emoji.

I guess Chrome on Linux only uses PNGs in an emoji font.
It is okay to provide EmojiOne in a format compatible to NotoColorEmoji, so that Chrome on Linux will be able to display it?
It will also enable the use on Android 5.0 and later, to replace stock emoji font.

Screenshot to prove color emoji ability of Chrome on Linux, version 53.0.2785.116 (64-bit), on ArchLinux latest version:

![image](https://cloud.githubusercontent.com/assets/1808930/19086937/ca6bfbd0-8a35-11e6-855a-034bac911b75.png)

**Comment by 13rac1** [comment]
Ah yes, Chrome has recently finally added support for a color font format in Linux. I've got plans to add the CBDT format to [SCFBuild](https://github.com/eosrei/scfbuild) , but you know... time... 

FWIW Long term, the only "web" solution is SVGinOT. These PNG formats (Google's and Apple's) are useful only for system fonts. Too large for web use.

**Comment by IgnoredAmbience** [comment]
Firefox appears to be able to display the Noto font glyphs as well, albeit with some `line-height` calculation issues _(not shown below)_, was this always the case?
(Hacked the CSS a bit in the preview, and my Fontconfig overrides)
(Your comment regarding SVG being better than PNG still stands also!)

![screen shot 2016-10-25 at 11 28 11](https://cloud.githubusercontent.com/assets/98555/19680569/82e4d9ae-9aa6-11e6-9ea5-f6e54510d9b7.png)

**Comment by jobukkit** [comment]
Firefox has anti-aliasing issues with the Noto font.

Chrome:

![Noto antialiasing in Chrome](http://www.jopv.net/uploads/chrome-noto-antialias-cropped.png)

Firefox:

![Noto antialiasing in Firefox](http://www.jopv.net/uploads/firefox-noto-antialias-cropped.png)

**Comment by 13rac1** [comment]
@edgemaster Not to my knowledge, I believe this is a new addition.

**Comment by ovr** [comment]
@eosrei 

> Ah yes, Chrome has recently finally added support for a color font format in Linux. I've got plans to add the CBDT format to SCFBuild 

Are you planing to support it? I created a similar problem in original `emojione` repo https://github.com/Ranks/emojione/issues/441, looks like it's similar problem

**Comment by 13rac1** [comment]
I have plans to implement support in SCFBuild, but it's not high on my priority list. Too many other things to do right now. Will I get to it? Definitely maybe.

**Comment by marsjaninzmarsa** [comment]
How Firefox (and others) will react to font with all glyphs encoded both in SVG and CBDT? That should cover all possible cases under Linux.

**Comment by max-baz** [comment]
FYI: there is a TTF file in [Ranks/emojione](https://github.com/Ranks/emojione) that provides colorful EmojiOne for Chrome on Linux 🎉 

However, there is a problem with glyph alignment that prevents it from being used, I'm trying to solve it in https://github.com/Ranks/emojione/issues/441 - if anyone could give me a hint, that would be awesome! We are one step away from having colorful EmojiOne on Chrome, people 😜

**Comment by m13253** [comment]
> FYI: there is a TTF file in Ranks/emojione that provides colorful EmojiOne for Chrome on Linux 🎉

It works and looks good.

![untitled](https://cloud.githubusercontent.com/assets/1808930/25386531/42bd7f5a-29fa-11e7-9bf2-256c4055aa02.png)

**Comment by max-baz** [comment]
@m13253 are the icons centered on the line for you? for me they are not, so for example typing emoji next to a text shows emoji too high above comparing to the text. Try with different font sizes on different pages. I had to change the font to move all characters down, it made things better, but still not ideal.

The old SVG font (the black and white one) is always centered, much better positioned in the text. That's the final issue I was referring to 😉

**Comment by m13253** [comment]
> are the icons centered on the line for you?

Yes they are.
I'm not sure what the reason is. It might be related to the font of the text?

**Comment by max-baz** [comment]
Not sure, this is reproduced even on Github. 

The TTF file provided by EmojiOne:

![image](https://cloud.githubusercontent.com/assets/1177900/25388317/d84d3466-29cd-11e7-9ba7-da3feace535f.png)

With my custom adjustments to the font:

![image](https://cloud.githubusercontent.com/assets/1177900/25388363/00335a1e-29ce-11e7-9b56-f888e24243ca.png)

**Comment by m13253** [comment]
The font I downloaded is the "Android" version here:
https://www.emojione.com/developers/download

What's your version? Install the same version as me and test if the problem resists.

**Comment by max-baz** [comment]
Ah, I used the "Apple" one 🙂 
Android version is in fact positioned correctly :+1:

**Comment by m13253** [comment]
This is my rendering:

![image](https://cloud.githubusercontent.com/assets/1808930/25388774/4d651c04-2a01-11e7-903d-95fc9d0b9b2b.png)

**Comment by max-baz** [comment]
Then I guess this issue can be closed, there's nothing left to do, the font works 🙂
