### ISSUE TITLE
Adding Emojis to Onboard (Ubuntu default virtual onscreen keyboard)?

### ISSUE THREAD

**Issue by kq01526** [eosrei/emojione-color-font#58]
Hi @eosrei ,

the Onboard devs are looking at how they could implement color Emojis into Onboard (the default virtual onscreen keyboard of Ubuntu desktop), see following thread:

https://bugs.launchpad.net/onboard/+bug/1615575

Do you possibly have any advice on how to do this ideally?

Regards

**Comment by 13rac1** [comment]
Thanks for the heads up! I've answered on Launchpad.
