### ISSUE TITLE
can support Emoji t-shirt U+FE4CF

### ISSUE THREAD

**Issue by catcat520** [eosrei/emojione-color-font#60]
EmojiOneColor-SVGinOT-1.3
WIN7

👕 󾓏 &#xfe4cf; 

"👕": ["U+1F455", "t-shirt", "1f455", ["", "U+E70E"], ["", "U+E5B6"], ["", "U+E006"], ["󾓏", "U+FE4CF"]],

thank you very much

**Comment by Crissov** [comment]
You’ve listed four PUA code-points (i.e. from private-use areas and without interoperable meaning). What are they intended to do?

**Comment by 13rac1** [comment]
@catcat520 This project tracks [EmojiOne](https://github.com/Ranks/emojione/) as the SVG upstream source, plus the minor addition of [Unicode Power Symbols](http://unicodepowersymbol.com/). 0xFE4CF is part of the [PUA](https://en.wikipedia.org/wiki/Private_Use_Areas) and isn't specified as a t-shirt. I will support if you can convince EmojiOne to support it.

@Crissov These show up in Android. 0xFE4CF seems to be PUA use by Google: http://www.iemoji.com/view/emoji/411/people/t-shirt No idea why.... ?!?

**Comment by Crissov** [comment]
Uh, Unicode keeps a list of [Shift-JIS codes originally used by Japanese telcos](http://unicode.org/Public/UCD/latest/ucd/EmojiSources.txt) and the original proposal also contained an [annex L2/10-132](http://www.unicode.org/L2/L2010/10009-emojidata.pdf) which has the actual Unicode PUA codes including the astral ones used by G-Mail. 

I’m not sure it would make sense to map the PUA codes to the respective glyphs so old content could be viewed successfully with the font. Once [scfbuild#5](https://github.com/eosrei/scfbuild/issues/5) is fixed this should be simple to achieve.

|  | Code | Docomo | KDDI | Softbank | G-Mail |
| --- | --- | --- | --- | --- | --- |
| Unicode | 1F455 | E70E | E5B6 | E006 | FE4CF |
| ShiftJIS | — | F9B3 | F7E6 | F946 | — |
