### ISSUE TITLE
Error in Windows script? No emojis in Firefox after installation

### ISSUE THREAD

**Issue by Flexxxo** [eosrei/emojione-color-font#61]
Hello,

I just test the Windows script. It created the font and I installed it.

I Firefox I still see the boxes and not the Emojis e.g. on this page:
http://emojipedia.org/unicode-7.0/

This is part of the scripts output with at least one error (?) message at the end:

C:\Users\Standard\Downloads\EmojiOneColor-SVGinOT-Win-1.3>install
Checking if Segoe UI Emoji is installed
Checking if Segoe UI Symbol is installed.
Checking if prerequisites are installed.
Ensuring the latest FontTools is installed.
Collecting https://github.com/behdad/fonttools/archive/master.zip
  Downloading https://github.com/behdad/fonttools/archive/master.zip (726kB)
    100% |████████████████████████████████| 727kB 319kB/s
Installing collected packages: fonttools
  Found existing installation: fonttools 0+unknown
    Uninstalling fonttools-0+unknown:
      Successfully uninstalled fonttools-0+unknown
  Running setup.py install for fonttools ... done
Successfully installed fonttools-0+unknown
Creating new Segoe UI Symbol font from EmojiOne
**c:\users\standard\appdata\local\programs\python\python36-32\lib\site-packages\fo
ntTools__init__.py:11: RuntimeWarning: versioneer: no suitable tags
  **import**('warnings').warn("versioneer: %s" % v['error'], RuntimeWarning)**

Could this be the reason why the Emojis don't show up? I checked the font created by the script and also cannot find the emojis v9 there.

**Comment by 13rac1** [comment]
Hmm... That error message _shouldn't_ be an issue since it's just a warning, but this the first I've seen it. I've got another issue right now regarding switching to the latest full release since the required code is now available. Can you try installing the latest full version instead of the master?

**Comment by Flexxxo** [comment]
Sorry if this sounds stupid but where to find this latest version?

**Comment by 13rac1** [comment]
No problem! Not stupid.

`pip install fonttools`, then comment out the install in the `install.cmd` before you run it. You may need to uninstall it first.

This is how it works on Ubuntu/Linux:

```
$ pip install fonttools
Collecting fonttools
  Downloading fonttools-3.1.2-py2.py3-none-any.whl (643kB)
    100% |████████████████████████████████| 645kB 668kB/s 
Installing collected packages: fonttools
Successfully installed fonttools-3.1.2
```

Should be the same for you.

**Comment by Flexxxo** [comment]
Thanks a lot!
1. Did uninstall fonttools using pip uninstall fonttools.
2. Installed the latest version using pip install fonttools (result exactly as in your example on Ubuntu).
3. Commented out the install fonttools line in install.cmd.
4. Ran install.cmd and installed the created font.
5. Rebooted.

When opening this page with V7 Unicode Emojis in Firefox I still see boxes with codes but no emojis:
http://emojipedia.org/unicode-7.0/

But I am supposed to see them there if the Segoe UI was modified succesfully, shouldn't I? Or am I mistaken / misunderstanding something?

Is it possible to check for the existence of the emojis by using the Windows Character Map or won't this work due to the technique of SVG in TTF which the Character Table application probably doesn't support?

Thanks in advance!

**Comment by 13rac1** [comment]
> But I am supposed to see them there if the Segoe UI was modified succesfully, shouldn't I? Or am I mistaken / misunderstanding something?

You should see them.

> Is it possible to check for the existence of the emojis by using the Windows Character Map or won't this work due to the technique of SVG in TTF which the Character Table application probably doesn't support?

![emoji in charmap](https://cloud.githubusercontent.com/assets/195061/20643878/1cae35c6-b3d9-11e6-85a0-e8cc7263cc87.png)

Not all of them are visible, but the b&w forms will display.

Are you running the current version of Win10?

**Comment by 13rac1** [comment]
No reply. Closing.
