### ISSUE TITLE
Black & white designs?

### ISSUE THREAD

**Issue by nclm** [eosrei/emojione-color-font#62]
EmojiOne now provides [their own monochrome designs](https://github.com/Ranks/emojione/tree/master/assets/svg_bw). I guess they are (at least partly) made and adjusted manually, so they may be better than stroke-only designs generated on the fly.
After some comparisons, could they be used as replacement in the font?

**Comment by 13rac1** [comment]
Oh look at that! They finally did it. Yes, I can switch to these versions.

**Comment by Crissov** [comment]
Note that they also provide their own font and no longer link to this project.

**Comment by 13rac1** [comment]
So, they dropped Linux and Windows support? Half of this project is just making the fonts work as default emoji fonts. I don't think they are aware of that.

**Comment by 13rac1** [comment]
Huh... Finally had some time to check this out. The duplicate B&W glyphs are not included. 
```
$ ls emojione/assets/svg -1 | wc
   1832    1832   22514
ls emojione/assets/svg_bw -1 | wc
   1403    1403   15728
```

This is going to be a lot more work. The "simple", but terrible method is 429 symlinks. The correct method is https://github.com/eosrei/scfbuild/issues/5 Not sure if there's a better way...

**Comment by 13rac1** [comment]
Closing due to #71
