### ISSUE TITLE
Breaks non-breakable spaces

### ISSUE THREAD

**Issue by nclm** [eosrei/emojione-color-font#63]
I had this bug on my Linux system for months but never investigated further. Then today I was playing with emoji fonts and fontconfig files and discovered it comes from here.

**Non-breakable spaces appears too wide.**
- Here’s how spaces appear (before `:`, `»`, `!`; after `«`) using DejàVu and no emoji font:
  ![spaces_dejavu](https://cloud.githubusercontent.com/assets/923008/19837125/916e8b9e-9eb3-11e6-8f01-d468a7dd327e.png)
- Here’s how it appears with Bitstream Vera, the emoji font and fonts.conf:
  ![spaces_bsvera](https://cloud.githubusercontent.com/assets/923008/19837123/9169a714-9eb3-11e6-862f-338991700162.png)
  (Ignore the ‘Standard spaces’ line, they are actually non-breakable spaces, but MediaWiki — where I was testing this — automatically replaces standard with non-breakable where necessary)
- Comparison:
  ![spaces_bsvera dejavu](https://cloud.githubusercontent.com/assets/923008/19837124/916d1c82-9eb3-11e6-937f-83d7d90defc1.png)

The wideness of this space looks weird and over time it is distracting when reading.

I think Bitstream Vera itself is fine. The emoji font doesn’t contain a non-breakable space character, but it does contain a simple space one, which may be the one that has larger metrics; and in a way or another `&nbsp;` defaults back to it.

Using Firefox on Linux. Webkit/Blink browsers seem to display fine.

**Comment by 13rac1** [comment]
Huh. I actually use the exact space width of Deja Vu and Vera: https://github.com/eosrei/emojione-color-font/blob/b6d5340ce0bbfe6dc5676038550cb296da023501/scfbuild.yml#L13-L14

_`.ttx` files created with `ttx` from fonttools._

`unitsPeEm`:
DejaVuSans.ttx: `<unitsPerEm value="2048"/>`
Vera.ttx: `<unitsPerEm value="2048"/>`

"space" width:
DejaVuSans.ttx: `<mtx name="space" width="651" lsb="0"/>`
Vera.ttx: `<mtx name="space" width="651" lsb="0"/>`

Hmm... problem is the "nbsp" width:
DejaVuSans.ttx: `<mtx name="nonbreakingspace" width="651" lsb="0"/>`
Vera.ttx: `<mtx name="nonbreakingspace" width="1303" lsb="0"/>`

Not sure what I can do about this... Could build a merged version like the Windows version??? I don't understand why Vera nbsp is so much bigger.

**Comment by nclm** [comment]
Good find. There’s probably some place to bug report for Vera. Thanks!

**Comment by nclm** [comment]
I sent an e-mail to `fonts(@)gnome(.)org` which [appears to host](https://www.gnome.org/fonts/) Bitstream Vera.

I think this bug can be closed as it does not belong here.

Unless… can you set your own `U+00A0` with a width of 651 in the EmojiOne font and make it priority in place of Vera’s one?

**Comment by 13rac1** [comment]
I could create the `U+00A0`, but since Vera is the config default it will override. Not much I can do...
