### ISSUE TITLE
EmojiOne font replacing numbers, asterisk, pound within Google Chrome

### ISSUE THREAD

**Issue by tlhunter** [eosrei/emojione-color-font#64]
Font version 1.3.1
    Linux 4.6.4-040604-generic #201607111332 SMP Mon Jul 11 17:34:50 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
    Installed via PPA
    Google Chrome Version 55.0.2883.35 beta (64-bit)

The following symbols, when rendered in Google Chrome, display black and white fonts from `EmojiOne Color` instead of the base font:

> 0123456789#*

Screenshot:

![2016-11-04-104140_1008x165_scrot](https://cloud.githubusercontent.com/assets/551402/20016087/4bff63b4-a27b-11e6-986d-675f9cdcb256.png)

This only happens in some situations, e.g. it doesn't typically happen when the base font is a monospace. Also doesn't affect other applications such as Firefox.

Font computing stuff:

![2016-11-04-104623_4480x1440_scrot](https://cloud.githubusercontent.com/assets/551402/20016314/25faedcc-a27c-11e6-892e-33d719aaa000.png)

**Comment by 13rac1** [comment]
Did you manually install the font previously? I've removed those characters in 1.3: https://github.com/eosrei/emojione-color-font/commit/e1a34da33493ee2966012cc6467ad519dfc518d3

**Comment by tlhunter** [comment]
That was it, I had an old version manually installed and the more recent PPA, downloading the tarball and running uninstall.sh fixed it.
