### ISSUE TITLE
Add Ubuntu Zesty (17.04) PPA to launchpad

### ISSUE THREAD

**Issue by michallepicki** [eosrei/emojione-color-font#68]
Ubuntu 17.04 was released. After upgrading and modifying PPAs for newer version, I got this error:
![obraz](https://cloud.githubusercontent.com/assets/4972756/25039827/1125f7ee-2106-11e7-90e8-b84a4b33e9b8.png)

**Comment by 13rac1** [comment]
Yes. To be expected, haha, it was released yesterday.

**Comment by 13rac1** [comment]
Copied both fonts-emojione-svginot and fonts-twemoji-svginot to Zesty. Untested, but should be fine. Let me know if there are any issues. 🤞 *for fontconfig*

**Comment by michallepicki** [comment]
Works great, thank you
