### ISSUE TITLE
Update EmojiOne icons to version 2.2.7

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [eosrei/emojione-color-font#69]
The latest version of EmojiOne Color font (v1.3) released in 25 Jul 2016, but the latest version of EmojiOne  is [released](https://github.com/Ranks/emojione/releases) in 2.2.7 after your release. Can you update EmojiOne icons to version 2.2.7?

**Comment by 13rac1** [comment]
I'll double check. I've been watching and updating my fork of emojione. I don't think there are any significant SVG changes.

**Comment by KrasnayaPloshchad** [comment]
I suggest tha last version of EmojiOne Color font can based on this version of EmojiOne, than discontinued in favor of EmojiTwo Color font.

**Comment by 13rac1** [comment]
I updated the two SVG changed in v2.7.7 with https://github.com/eosrei/emojione-color-font/commit/27b74b4a47cc44afbc52531461a9703ed23f8535 this afternoon.

I'll keep an eye on EmojiTwo, but since there's nothing to implement right now I'd rather not leave this issue open. Thanks!
