### ISSUE TITLE
Huge Emoji

### ISSUE THREAD

**Issue by iloxmn** [eosrei/emojione-color-font#70]
![wp_ss_20170418_0006](https://cloud.githubusercontent.com/assets/22426402/25107982/2afbc85e-2405-11e7-985f-0c733996b1db.png)
Isn't it too big?

**Comment by 13rac1** [comment]
Is this Windows phone??? Looks like it?

How do I reproduce this issue?

**Comment by iloxmn** [comment]
Yes, yes and yes

Download my app Font Book (It's in Windows Store)
Open your font
Then then type some emoji and you'll see that.
 
I'm just trying to modify this font to replace default Segoe UI Emoji and I notice that your emoji font might have some issues.

**Comment by 13rac1** [comment]
I don't have a Windows phone.

This may be an issue with the overall build since I haven't rebuilt since the format fix to SCFbuild. Can you test the Xerographer fonts: https://xerographer.github.io/ ?

**Comment by iloxmn** [comment]
![screenshot 22](https://cloud.githubusercontent.com/assets/22426402/25114584/299bc3ec-2432-11e7-8a32-4ac0f92a7fc9.png)

It's a Universal Windows App

And I've test the "Reinebow" font before and it looks pretty good

**Comment by 13rac1** [comment]
Ah ha! I'll rebuild. I've actually never used the Windows store on my desktop. This laptop is full time Linux.

**Comment by iloxmn** [comment]
Ok 😊. And you should try it sometime, it's been about 5 years since Windows have Windows store.

**Comment by 13rac1** [comment]
I just did a new rebuild and release of twemoji-color-font: https://github.com/eosrei/twemoji-color-font/releases/tag/v1.2 It'll probably work fine for you.

**Comment by iloxmn** [comment]
It works pretty good. 
Thanks!  
![wp_ss_20170503_0002](https://cloud.githubusercontent.com/assets/22426402/25650115/38717c40-300d-11e7-9394-73d03150d362.png)

**Comment by 13rac1** [comment]
Ok great! Thank you for testing it. I need to do a few more tests then I can make a final release of this font.
