### ISSUE TITLE
Update EmojiOne icons to version 3.0

### ISSUE THREAD

**Issue by KrasnayaPloshchad** [eosrei/emojione-color-font#71]
The developer says this release “brings about many breaking changes”.

**Comment by 13rac1** [comment]
😞  There's a very important breaking change: The license for SVG graphics. I cannot update this project further with SVG.

From the readme:https://github.com/Ranks/emojione/blob/844221d8931592dcc188caa74b7cad085a186bc8/README.md#emojione-version-3

> EmojiOne launched version 3.0 in 2017, which has several licensing options available. PNG 32px, 64px, and 128px as well as 32px and 64px sprites are available for digital use, with attribution. See http://emojione.com/developers/free-license for more information on usage and attribution requirements.

> Premium Licenses are available for larger PNG assets and SVG assets, for digital and print use. See http://emojione.com/developers/premium-license for more information or to obtain a Premium License.

From the premium license:

> May not include icons in open-source projects.

My work with EmojiOne SVG graphics has been specifically blocked. It is possible to [embed the PNG images in SVG files](https://pixelambacht.nl/lapislegit/), but even the [Free license](https://d2gx6z0drfblcq.cloudfront.net/license-free.pdf) is restrictive enough that I'd rather avoid it:

>  Any EmojiOne Artwork used under this agreement must  adhere to the following guidelines:
> * cannot exceed the size of 128 x 128 pixels
> * .svg file format use is not allowed

I will make one final release of this project, then deprecate it. I will continue to update: https://github.com/eosrei/twemoji-color-font when Unicode 10 is released.

Update: Twemoji now has Unicode 10

**Comment by Crissov** [comment]
Would you consider to support [Emoji Two](/Crissov/emojitwo) instead? It's a fork of Emoji One 2.2.7 which I intend to keep updated. Alas, I will need the help of some designers willing to license their work under CC-BY-4.0, because I'm rather untalented and inexperienced in graphic design.

PS: 🎶 Suicide is painless, 🎶 it brings on many changes. 🎶

**Comment by 13rac1** [comment]
@Crissov Interesting idea! I'm willing to support EmojiTwo when there is a Unicode 10 release. The graphic design is a lot of work. Good luck! :D

**Comment by KrasnayaPloshchad** [comment]
I’m not sensed such changes, sorry.
