### ISSUE TITLE
N̼̬̭̥̥̊̓͌ is not seen properly on chrome/linux after installing the ubuntu package

### ISSUE THREAD

**Issue by gnuton** [eosrei/emojione-color-font#72]
N̼̬̭̥̥̊̓͌ utf char is not seen correctly if emojione-color-font is installed on ubuntu xenial

Please include:
- Font version 1.3
- Screenshots - N̼̬̭̥̥̊̓͌  gets 2 squares above and under the N if this font is enabled 
- Operating system - ubuntu linux xenial
- Steps to reproduce install the font and see this char  N̼̬̭̥̥̊̓͌  in chrome Version 56.0.2924.87 (64-bit)

**Comment by 13rac1** [comment]
Please add a screenshot showing this problem.

**Comment by 13rac1** [comment]
May be related to #36

**Comment by 13rac1** [comment]
I suspect this is an additional example of #40.

**Comment by DeeDeeG** [comment]
Screenshot on Firefox from 17.04 (Zesty)

![things-above-and-below-n](https://cloud.githubusercontent.com/assets/20157115/26125106/f20f67a2-3a4e-11e7-8306-e449b80f9b4c.png)

Chromium:

![chromium-n](https://cloud.githubusercontent.com/assets/20157115/26125476/441a43c2-3a50-11e7-9760-00bc0176a098.png)

**Comment by 13rac1** [comment]
Hmm.. FWIW It doesnt work correctly in Chrome without this font package installed either. It's not as broken, but it's still broken compared to Firefox. There's nothing I can do about this. It's a good example of #40

Here's a "more broken" with font installed image:
![morebroken](https://cloud.githubusercontent.com/assets/195061/26133161/23bed476-3a5a-11e7-8ce7-8d3c1e63d8ce.png)

DeeDeeG's screenshot is what I see with the font uninstalled.

**Comment by DeeDeeG** [comment]
Somehow after installing I never got the boxes.

(Speculating a bit: I think maybe 17.04 has more fonts than 16.04... or Ubuntu Mate has more fonts than vanilla Ubuntu... or they tweaked/fixed the font stack somewhere between 16.04 and 17.04.)

**Comment by 13rac1** [comment]
I consider this issue out of scope of this project and the next release of this project is the last. Switch to https://github.com/eosrei/twemoji-color-font
