### ISSUE TITLE
Is it supported on the terminal ?

### ISSUE THREAD

**Issue by ifzm** [eosrei/emojione-color-font#75]
OS：Ubuntu 16.04 LTS
Shell：oh-my-zsh

I use the oh-my-zsh emoji plugins to see and find it still gray.

**Comment by 13rac1** [comment]
SVG in OpenType is not supported on any terminal to my knowledge. It's not up to your shell. I've seen discussion of getting the CBDT/CBLC fonts working, but haven't researched it myself: https://github.com/Ranks/emojione/tree/master/extras/fonts#google-font---emojione-androidttf

**Comment by ifzm** [comment]
thank your，i will try your advice )

**Comment by sparcut** [comment]
@ifzm Few months old, but any luck with color emoji in zsh (+ oh-my-zsh)?
