### ISSUE TITLE
Color emojis in PhantomJS?

### ISSUE THREAD

**Issue by pamelafox** [eosrei/emojione-color-font#76]
Hello!

I am using High Charts Export Server (https://github.com/highcharts/node-export-server)
which uses PhantomJS to render images.

My charts have emojis in them, and I am running the server on an Amazon Linux Box, so I am trying to get the emojis to appear in the rendered charts.

I have now succeeded in using EmojiOne to get the emojis to appear as black & white glyphs:
https://woebot-graphs.s3-us-west-2.amazonaws.com/FAKEUSERID1/D3j4BuXJfhwfHDNGWayZwubD/weeklygraph.png
Thank you!

Do you think there is any hope in getting PhantomJS to render the color glyphs, or are they unable to due to an underlying limitation of the headless browser?

I'm trying to figure out if it's worth it to try to get color emojis working, or if it is futile. Thanks!

**Comment by 13rac1** [comment]
Hi! PhantomJS uses Webkit in the backend. I don't have any idea what it's color font support is. You can check with: https://pixelambacht.nl/chromacheck/ You may have better luck with headless Chrome. Although for less hassles for right now, I'd use PNGs in your project.

**Comment by pamelafox** [comment]
Okay, thanks for the reply! I'll close this issue.
