### ISSUE TITLE
Outlook.com

### ISSUE THREAD

**Issue by timea-techgirl** [eosrei/emojione-color-font#78]
Hello, after installing this font, emojis in my email account, outlook.com have become white and colourless. I can't recognise and find emojis well. They were coloured before installing the font. This is a major issue for me as I always write emails and use a lot of emojis. I don't want to uninstall this just because of one site.

- Font v1.3
- Windows 7 Ultimate x64
- Open microsoft outlook.com and login. Click on the smiley icon and all the emoticons are white and colourless.

**Comment by 13rac1** [comment]
This font is only supported in color by Edge and Firefox. Are you using Chrome or IE11?

**Comment by timea-techgirl** [comment]
Yes, chrome but how did it impact outlook.com? Before it had colour.

**Comment by 13rac1** [comment]
This font is designed to replace your emoji characters. You replaced the emoji with color versions only supported in Edge and Firefox. It's a limitation of the chrome browser. It's not supported.
