### ISSUE TITLE
Missing fonts after installing EmojiOne

### ISSUE THREAD

**Issue by tercerapersona** [eosrei/emojione-color-font#80]
Latest version from ppa:eosrei/fonts

After installed EmojiOne fonts, I think my Ubuntu GNOME has lost fonts or just misconfigured.
I've already restarted but still the same.

For example: http://imgur.com/a/iJbeK

**Comment by 13rac1** [comment]
You caught me just as I was away from the computers awhile. What version of Ubuntu GNOME? Which applications?

**Comment by 13rac1** [comment]
Closing. No response.
