### ISSUE TITLE
Add Unicode 10.0 support

### ISSUE THREAD

**Issue by jorgicio** [eosrei/emojione-color-font#81]
This is not exactly an issue, but kinda a bump request. Unicode 10.0 was just released yesterday.
I'll leave this as a suggestion.

Thanks in advance.

**Comment by 13rac1** [comment]
Sorry. I cannot. The EmojiOne license has changed and I can no longer use their SVG graphics for this project. All further development will continue in https://github.com/eosrei/twemoji-color-font only.

More details in #71

**Comment by jorgicio** [comment]
Ok, sorry then. Thank you.
BTW, I upgraded the Twemoji package to the latest version.
