### ISSUE TITLE
[Windows] Font-Cache When Replacing Segoe UI Emoji

### ISSUE THREAD

**Issue by ghost** [eosrei/emojione-color-font#84]
You probably need to add this to the installation batch:
<a href="https://github.com/eladkarako/fonts-windows/blob/master/font_cache_fix.cmd">github.com/eladkarako/fonts-windows/blob/master/font_cache_fix.cmd</a>

**Comment by 13rac1** [comment]
Thank you! Do I just run this? Any interest in PRing it to https://github.com/eosrei/twemoji-color-font ?

**Comment by ghost** [comment]
>Do I just run this?

Appending:
```cmd
del /f /q   "%SystemRoot%\System32\FNTCACHE.DAT"     2>nul >nul
del /f /q   "%SystemRoot%\SysWOW64\FNTCACHE.DAT"     2>nul >nul
del /f /q   "%SystemRoot%\System32\StaticCache.dat"  2>nul >nul
del /f /q   "%SystemRoot%\SysWOW64\StaticCache.dat"  2>nul >nul
```
to the end of the installation batch-file should be good-enough.

>Any interest in PRing

nope. ^_^
