### ISSUE TITLE
On Linux ask for a different font

### ISSUE THREAD

**Issue by Mte90** [eosrei/emojione-color-font#85]
I am using the Oxygen font that doesn't include emoji but when I execute the install I get to many issue on font rendering for different sizes so I changed all the config file and replace to Oxygen.
Ii will be useful to have better info for that during the installer

**Comment by 13rac1** [comment]
I'm not sure how this would be better implemented in the installer. I provide a package, an installer, and just the bare font. I cannot support custom installs though.

**Comment by Mte90** [comment]
The fontconfig file contain Bitstream hardcoded maybe the installer can ask for a different font to use it on it :-)

**Comment by hadess** [comment]
The new fontconfig 2.12.5 includes rules to mark "Emoji One" (and a number of other freely available emoji fonts) as an emoji font. If pango is in the stack (for GTK+ applications for example), an "emoji" font will automatically be selected for emoji codepoints.

The fonts.conf should probably not be installed with this version of fontconfig.

**Comment by apollo13** [comment]
@hadess Just to make sure that I understand you correctly. This means that fontconfig will now automatically use emojies from "Emoji One" for all; even if they also exist in "DejaVu" for instance?

**Comment by hadess** [comment]
> @hadess Just to make sure that I understand you correctly. This means that fontconfig will now 
> automatically use emojies from "Emoji One" for all; even if they also exist in "DejaVu" for instance?

I'm not sure whether DejaVu has any emojis in its font, but that's what would happen if it did.

**Comment by 13rac1** [comment]
DejaVu has many characters considered emoji.

Closing issue, I'm looking into some ideas for solutions to this question, but it will not be addressed in this project. Switch to: https://github.com/eosrei/twemoji-color-font
