### ISSUE TITLE
Ubuntu: Don't replace Ubuntu Font with Bitstream Vera [feature request]

### ISSUE THREAD

**Issue by salim-b** [eosrei/emojione-color-font#86]
I don't like Bitstream Vera replacing (in large parts) the default Ubuntu system font. Would it be possible for the Ubuntu packages to provide a "neutered" version of the Ubuntu Fonts which don't include the emoji codepoints instead of Bitstream Vera?

Issue https://github.com/eosrei/emojione-color-font/issues/72 seems (loosely) related.

**Comment by 13rac1** [comment]
First, I've been distract with other projects, but this project is deprecated. See #71

The default system font on Ubuntu 16.04 is DejaVu. It is literally just a version of Bitstream Vera with additional codepoints. [[src](https://en.wikipedia.org/wiki/DejaVu_fonts)]
> The DejaVu fonts are modifications of the Bitstream Vera fonts designed for greater coverage of Unicode, as well as providing more styles.

You may be using a different font? If so, newer versions of fontconfig support specific a specific `emoji` font family. It may fix this issue. I plan to upgrade: [twemoji-color-font](https://github.com/eosrei/twemoji-color-font) to support it.

In general, this entire project was about half fighting fontconfig. I wish emoji-less fonts were standard as they are on Win/Mac.

**Comment by salim-b** [comment]
> this project is deprecated

Thanks for the hint, I didn't realize that.

> The default system font on Ubuntu 16.04 is DejaVu.

Well, that's not true (at least not for most latin-character languages). The default system font in Ubuntu 16.04 actually is [_Ubuntu_](http://font.ubuntu.com/) (and this [has been the case since version 10.10](https://en.wikipedia.org/wiki/Ubuntu_(typeface))).

The result of installing `emojione-color-font` is a weird mix of still retaining the Ubuntu font in some places (like window decorations, dashboard/hud etc.) but at the same time introducing Bitstream Vera for everything else like the texts inside system pop-ups, Firefox browser etc. It doesn't look good...

> newer versions of fontconfig support a specific `emoji` font family. It may fix this issue. I plan to upgrade: [twemoji-color-font](https://github.com/eosrei/twemoji-color-font) to support it.

Sounds promising! I don't really know about `fontconfig` and stuff, but do I understand you right that after this planned upgrade no system font gets replaces by Bitstream Vera anymore and `twemoji-color-font` would _only_ be used to display emojis?

**Comment by 13rac1** [comment]
> The default system font in Ubuntu 16.04 actually is Ubuntu (and this has been the case since version 10.10).

In the GUI. Ubuntu is your the default _Application_ font. The system font is DejaVu. :) Try it yourself.
```
$ fc-match -s | head -n5
Vera.ttf: "Bitstream Vera Sans" "Roman"
TwitterColorEmoji-SVGinOT.ttf: "Twitter Color Emoji" "Regular"
DejaVuSans.ttf: "DejaVu Sans" "Book"
DejaVuSans-Bold.ttf: "DejaVu Sans" "Bold"
DejaVuSans-Oblique.ttf: "DejaVu Sans" "Oblique"
```
Ubuntu isn't even listed. Can you provide a screenshot of this weird mix? You may want to install the updated fontconfig in #83 (it'll be part of the final release, I'll handle it this week)

> I understand you right that after this planned upgrade no system font gets replaces by Bitstream Vera anymore and twemoji-color-font would only be used to display emojis?

Bitstream Vera will continue to replace DejaVu AFAIK, but they are the same glyphs so it doesn't matter.

**Comment by salim-b** [comment]
> In the GUI. Ubuntu is your the default Application font. The system font is DejaVu.

Ok... Since I'm not really proficient in font related stuff I tried to google the difference between _system font_ and _application font_ – but without success. It's everywhere said that the _system font_ in Ubuntu would be the Ubuntu font family (and nothing particular about an _application font_).

> Try it yourself.

I get the the same result as you (except that the 2nd entry is `EmojiOneColor-SVGinOT.ttf`, of course). But does this command really produce the same _before_ installing `emojione-color-font`/`twemoji-color-font`?

> Can you provide a screenshot of this weird mix?

Below's a screenshot. It seems to be only Firefox and Thunderbird where the Ubuntu font was replaced with Bitstream Vera. I guess I was wrong stating that Bitstream Vera would also be _inside system pop-ups_ (I thought I've seem some but couldn't replicate it anymore – maybe it was just a Thunderbird calendar reminder pop-up).

![bildschirmfoto vom 2017-09-24 19-52-55](https://user-images.githubusercontent.com/20040931/30785145-28d55862-a162-11e7-9a36-b38f44da536c.png)

> You may want to install the updated fontconfig in #83 (it'll be part of the final release, I'll handle it this week)

If your final release will land this soon, I'll just wait 🙂 Thank you anyway!

**Comment by 13rac1** [comment]
It does:
```
$ sudo apt-get remove fonts-twemoji-svginot 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages will be REMOVED:
  fonts-twemoji-svginot
0 upgraded, 0 newly installed, 1 to remove and 50 not upgraded.
After this operation, 9,153 kB disk space will be freed.
Do you want to continue? [Y/n] 
(Reading database ... 582918 files and directories currently installed.)
Removing fonts-twemoji-svginot (1.2-1) ...
Processing triggers for fontconfig (2.11.94-0ubuntu1.1) ...
$ fc-match -s | head -n3
DejaVuSans.ttf: "DejaVu Sans" "Book"
DejaVuSans-Bold.ttf: "DejaVu Sans" "Bold"
DejaVuSans-Oblique.ttf: "DejaVu Sans" "Oblique"
```

Please try the config listed in the other issue.

**Comment by salim-b** [comment]
> Please try the config listed in the other issue.

Ok, I've patched `/etc/fonts/conf.avail/56-emojione-color.conf` with the [diff provided by jorgicio](https://github.com/eosrei/emojione-color-font/issues/83#issuecomment-326653683). What do I have to  do now to have the new conf take effect?

**Comment by 13rac1** [comment]
Generally the system will automatically pick up the change, but if not log out/in should cover it. If there's no change, then restart. If still no change, then there's a separate issue.

**Comment by salim-b** [comment]
The new conf file seems to fix the issue with the Mozilla apps: After a reboot everything's back to the Ubuntu fonts again! 🎉
