### ISSUE TITLE
Release EmojiTwo as an SVGinOT font

### ISSUE THREAD

**Issue by lofidevops** [eosrei/emojione-color-font#87]
This was mentioned in #71 - creating this issue for explicit tracking:

> I'm willing to support EmojiTwo when there is a Unicode 10 release. The graphic design is a lot of work. Good luck! :D

See also:
* https://github.com/EmojiTwo/emojitwo/issues/162 (upstream)
* https://github.com/EmojiTwo/emojitwo/milestone/1 (Unicode 10 milestone)

**Comment by 13rac1** [comment]
Closing this issue. Will assist with EmojiTwo when available.
