### ISSUE TITLE
Whats the deal with Chrome?

### ISSUE THREAD

**Issue by sparcut** [eosrei/emojione-color-font#88]
- **Font version:** 1.3 (current?)
- **Operating system:** Fedora 26 (Gnome 3.24.3)

Just wondering why Chrome (and Safari?) does not work with this font, I can see under OSX and Windows install you mention that it does not work, but you be able to ellaborate just out of intrest?

I thought there would've been an issue for this but can't find an open or closed one that relates to why color emojis don't work in Chrome.

**Comment by Crissov** [comment]
There are four (!) standardized (!) alternative methods to put colorful glyphs into font files. Two are based on vectors, two on bitmaps. All can be made to fall back to monochrome vectors, but are hard to impossible to combine in a single (then huge) font file. Three of them could be generated from SVG sources, but require different tools.

This project is not set up to generate more than one of these variants – currently. Furthermore, SVG files are no longer available freely and openly for the latest versions of Emojione, so this project is effectively stalled there.

**Comment by 13rac1** [comment]
All @Crissov said is correct. I'm busy with other projects, but I plan to add build add the Chrome/Android specific format to https://github.com/eosrei/twemoji-color-font since upstream is being updated and has a compatible license. I still believe this format should work in Chrome though.
