### ISSUE TITLE
Create deb file for launchpad PPA

### ISSUE THREAD

**Issue by 13rac1** [eosrei/emojione-color-font#9]
Need to create a PPA to install the font system-wide on Debian/Ubuntu

**Comment by 13rac1** [comment]
Blocked by ~~#2~~, ~~#16~~, and ~~#17~~.

**Comment by 13rac1** [comment]
I'll be creating a CBDT/CBLC format version of both fonts also, so this first package will include the SVGinOT format name.

`fonts-` vs `ttf-`: Looks like all newer font package names use the `fonts-` prefix: `fonts-noto`, `fonts-font-awesome`.

Probably `fonts-emojione-svginot` and later `fonts-emojione-cbdt`.

**Comment by 13rac1** [comment]
I'm not ready to add this to the readme yet, but if anyone is following this issue:

```
sudo apt-add-repository ppa:eosrei/fonts
sudo apt-get update
sudo apt-get install fonts-emojione-svginot
```

Note: Delete the existing font and fontconfig to use the PPA.

```
rm -f $HOME/.fonts/EmojiOneColor-SVGinOT.ttf
rm -f $HOME/.local/share/fonts/EmojiOneColor-SVGinOT.ttf
rm -f $HOME/.config/fontconfig/fonts.conf
```

@gentakojima Can you try it out?

**Comment by gentakojima** [comment]
Yay! Unfortunately, I'm currently using 16.04 (wily) and the PPA is not available for this version. You can easily make it available using the Launchpad website.

**Comment by 13rac1** [comment]
Haha! I just started with trusty. I'll add the others.

**Comment by gentakojima** [comment]
Oh, I've just changed wily to trusty in the apt definitions and it works out of the box. The package works great, the emojis started working right away after installing the package! :) (just tried the emojione one)

**Comment by 13rac1** [comment]
Awesome! Thank you!

I just added the twemoji version a half hour ago. I'm trying to just update both fonts at the same time, so I don't forget anything.

I was hoping to find a way to automatically create versions for all current distributions. The copy method works, I've just done it for 16.04, but somehow it's a feature request to do it automatically:
- [Bug #235064 “Implement multi-release support for packages” : Bugs : Launchpad itself](https://bugs.launchpad.net/launchpad/+bug/235064)
- [Bug #330711 ""same version already has published binaries in the... : Bugs : Launchpad itself](https://bugs.launchpad.net/launchpad/+bug/330711)

**Comment by 13rac1** [comment]
The official workaround: https://bugs.launchpad.net/launchpad/+bug/330711/comments/4 :cry: 

> The core problem is that you can't rebuild the same version more than once in a pool-based repository. You'd need to upload different builds (from each series) of the same binary version, and there's nowhere to put them because the indexes can only refer to one file in the pool for each version.
> 
> If you want to do it, the only solution is to bump the version. Ubuntu does this by appending ~hardy or ~intrepid, for example, to the version of the package.

**Comment by uniquePWD** [comment]
So I switched to the PPA and it's kinda destroyed the fonts in my Firefox and made everything a Serif.

**Comment by 13rac1** [comment]
@sabret00the Did you completely remove all existing ttf and conf files previously installed from your system? 

Could you try out the "tests" available in the tar.gz? It will compare your current system verses the expected configuration. You can also just download these two files: https://github.com/eosrei/emojione-color-font/tree/master/linux/tests

**Comment by 13rac1** [comment]
@sabret00the FWIW I just rechecked the PPA install on a 16.04 LiveCD and it's working as designed.

**Comment by uniquePWD** [comment]
@eosrei it returns

```
$ Downloads/tests/tests.sh
Fontconfig tests: UPDATE
```

**Comment by 13rac1** [comment]
@sabret00the You need **both** files in the same directory and you need to run it in the directory.

``` sh
cd Downloads/tests
./test.sh
```

If you have just one it'll create a new "expected results" file. It's just a simple bash script, check the file for details. Basically it compares a number of outputs from `fc-match` verses the expected outputs.

**Comment by uniquePWD** [comment]
At the bottom it says: `Fontconfig tests: FAIL`

[expected-results.test.txt](https://github.com/eosrei/emojione-color-font/files/254134/expected-results.test.txt)

**Comment by 13rac1** [comment]
Yes, what is the output. Please copy/paste.

**Comment by uniquePWD** [comment]
```
 ./tests.sh
diff current-results.test expected-results.test
Font: sans                                                         Font: sans
EmojiOneColor-SVGinOT.ttf: "Emoji One Color" "Regular"          |  Vera.ttf: "Bitstream Vera Sans" "Roman"
EmojiOneColor-SVGinOT.ttf: "Emoji One Color" "Regular"             EmojiOneColor-SVGinOT.ttf: "Emoji One Color" "Regular"

Font: sans-serif                                                   Font: sans-serif
EmojiOneColor-SVGinOT.ttf: "Emoji One Color" "Regular"          |  Vera.ttf: "Bitstream Vera Sans" "Roman"
EmojiOneColor-SVGinOT.ttf: "Emoji One Color" "Regular"             EmojiOneColor-SVGinOT.ttf: "Emoji One Color" "Regular"

Font: serif                                                        Font: serif
EmojiOneColor-SVGinOT.ttf: "Emoji One Color" "Regular"          |  VeraSe.ttf: "Bitstream Vera Serif" "Roman"
EmojiOneColor-SVGinOT.ttf: "Emoji One Color" "Regular"             EmojiOneColor-SVGinOT.ttf: "Emoji One Color" "Regular"

Font: mono                                                         Font: mono
EmojiOneColor-SVGinOT.ttf: "Emoji One Color" "Regular"          |  VeraMono.ttf: "Bitstream Vera Sans Mono" "Roman"
EmojiOneColor-SVGinOT.ttf: "Emoji One Color" "Regular"             EmojiOneColor-SVGinOT.ttf: "Emoji One Color" "Regular"

Font: monospace                                                    Font: monospace
EmojiOneColor-SVGinOT.ttf: "Emoji One Color" "Regular"          |  VeraMono.ttf: "Bitstream Vera Sans Mono" "Roman"
EmojiOneColor-SVGinOT.ttf: "Emoji One Color" "Regular"             EmojiOneColor-SVGinOT.ttf: "Emoji One Color" "Regular"

Font: Bitstream Vera Sans                                          Font: Bitstream Vera Sans
Vera.ttf: "Bitstream Vera Sans" "Roman"                            Vera.ttf: "Bitstream Vera Sans" "Roman"
EmojiOneColor-SVGinOT.ttf: "Emoji One Color" "Regular"             EmojiOneColor-SVGinOT.ttf: "Emoji One Color" "Regular"

Font: Bitstream Vera Serif                                         Font: Bitstream Vera Serif
VeraSe.ttf: "Bitstream Vera Serif" "Roman"                         VeraSe.ttf: "Bitstream Vera Serif" "Roman"
EmojiOneColor-SVGinOT.ttf: "Emoji One Color" "Regular"             EmojiOneColor-SVGinOT.ttf: "Emoji One Color" "Regular"

Font: Bitstream Vera Sans Mono                                     Font: Bitstream Vera Sans Mono
VeraMono.ttf: "Bitstream Vera Sans Mono" "Roman"                   VeraMono.ttf: "Bitstream Vera Sans Mono" "Roman"
EmojiOneColor-SVGinOT.ttf: "Emoji One Color" "Regular"             EmojiOneColor-SVGinOT.ttf: "Emoji One Color" "Regular"

Font: emoji                                                        Font: emoji
EmojiOneColor-SVGinOT.ttf: "Emoji One Color" "Regular"             EmojiOneColor-SVGinOT.ttf: "Emoji One Color" "Regular"
EmojiOneColor-SVGinOT.ttf: "Emoji One Color" "Regular"          |  Vera.ttf: "Bitstream Vera Sans" "Roman"

Font: Emoji One Color                                              Font: Emoji One Color
EmojiOneColor-SVGinOT.ttf: "Emoji One Color" "Regular"             EmojiOneColor-SVGinOT.ttf: "Emoji One Color" "Regular"
EmojiOneColor-SVGinOT.ttf: "Emoji One Color" "Regular"          |  Vera.ttf: "Bitstream Vera Sans" "Roman"

Font: Apple Color Emoji                                            Font: Apple Color Emoji
EmojiOneColor-SVGinOT.ttf: "Emoji One Color" "Regular"             EmojiOneColor-SVGinOT.ttf: "Emoji One Color" "Regular"
EmojiOneColor-SVGinOT.ttf: "Emoji One Color" "Regular"          |  Vera.ttf: "Bitstream Vera Sans" "Roman"

Font: Segoe UI Emoji                                               Font: Segoe UI Emoji
EmojiOneColor-SVGinOT.ttf: "Emoji One Color" "Regular"             EmojiOneColor-SVGinOT.ttf: "Emoji One Color" "Regular"
EmojiOneColor-SVGinOT.ttf: "Emoji One Color" "Regular"          |  Vera.ttf: "Bitstream Vera Sans" "Roman"

Font: Noto Color Emoji                                             Font: Noto Color Emoji
EmojiOneColor-SVGinOT.ttf: "Emoji One Color" "Regular"             EmojiOneColor-SVGinOT.ttf: "Emoji One Color" "Regular"
EmojiOneColor-SVGinOT.ttf: "Emoji One Color" "Regular"          |  Vera.ttf: "Bitstream Vera Sans" "Roman"

Fontconfig tests: FAIL
```

**Comment by 13rac1** [comment]
Since it is showing the font twice, it looks like you still have the original ttf and fontconfig installed. Do you? They must be removed.

**Comment by uniquePWD** [comment]
I removed them via the command line. Shall I re-remove them but this time manually?

**Comment by 13rac1** [comment]
I'm sure I follow what you mean by command line vs manually, but I recommend removing everything. Make it completely stock with no emoji (no fontconfig no ttf), then install just the package using apt-get.

**Comment by uniquePWD** [comment]
Removed the files via nautilus and then removed the repo before re-adding the repo and everything is back to normal. Thank you @eosrei
