### ISSUE TITLE
Emoji not scaled properly in Windows 10 On-screen keyboard

### ISSUE THREAD

**Issue by samdenty** [eosrei/emojione-color-font#90]
Font version: 1.3
OS: Windows 10 1709 build 16299.15
![image](https://user-images.githubusercontent.com/13242392/32405585-209a1660-c160-11e7-9fd3-c4052dfdd200.png)

**Comment by 13rac1** [comment]
Yes, I need to rebuild it, but I've delayed because this project is dead due to upstream. :( See #71 

Upgrade path: https://github.com/eosrei/twemoji-color-font
