### ISSUE TITLE
Scroll emoji is broken

### ISSUE THREAD

**Issue by gluons** [eosrei/emojione-color-font#92]
**Font version:**  fonts-emojione-svginot 1.3-1

**Screenshot:** ![screenshot-2017-11-20 scroll emoji](https://user-images.githubusercontent.com/4688092/33029182-8032e54c-ce4a-11e7-85ad-972b97102f40.png)

**OS:** Linux Mint 18.2 (Also happened on my previous OS Kubuntu 17.04)

**Steps to reproduce:** See it in https://emojipedia.org/scroll/

**Comment by 13rac1** [comment]
It works correctly in twemoji and this project has reached end of life. Please switch: https://github.com/eosrei/twemoji-color-font

**Comment by gluons** [comment]
OK. Thank you for informing me.
