### ISSUE TITLE
EmojiOne for Ubuntu Artful Aardvark

### ISSUE THREAD

**Issue by raqbit** [eosrei/emojione-color-font#94]
Currently only the Twemoji version is packaged for Artful Aardvark.
Is there any reason this isn't the case for the EmojiOne
version?

**Comment by 13rac1** [comment]
Yes, because this project is deprecated and only supports Unicode 9. Upstream changed their license. Only twemoji supports Unicode 10.

**Comment by 13rac1** [comment]
#71 for details.
