### ISSUE TITLE
not able to install in centos

### ISSUE THREAD

**Issue by vigneshindn** [eosrei/emojione-color-font#95]
[root@localhost EmojiOneColor-SVGinOT-Linux-1.3]# ./install.sh
EmojiOne Color font installer for Linux\n
Bitstream Vera font family not found. Please install it:
sudo apt-get install ttf-bitstream-vera
in centos , not able to install please give me a solution , thanks in advance

**Comment by 13rac1** [comment]
I don't run CentOS. I think this is the correct package: https://centos.pkgs.org/7/nux-dextop-x86_64/bitstream-vera-sans-fonts-1.10-19.el7.nux.noarch.rpm.html

**Comment by vigneshindn** [comment]
i tried this link earlier , even its not working...

**Comment by 13rac1** [comment]
The above link works. There are other font configs available If you don't want to install Bitstream Vera, but the auto-installer only works with it.
